spring.application.name=config-server
server.port=8888

eureka.client.service-url.defaulZone=http://localhost:8761/eureka

spring.cloud.config.server.native.search-locations=C:\\Config
spring.profiles.active=native